name: Deployment pipeline
on:
  push:
    branches:
      - master
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install modules
        run: yarn
      - name: Format Checking
        run: yarn test:format
      - name: Lint Checking
        run: yarn test:lint
  VercelDeploy:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
